language: rust

notifications:
  email:
    on_success: never
    on_failure: always

env:
  global:
    - secure: nIJ31R6hTk3oIjyJos3My5CvC/NPKR1cAuMuP5+5uDLDIMopbBYCOG9SIyVgwYTACRhTDDCqWaWUKGhMrG+AUbmcEEwXTNfFquvFM4KAkXUKPrRaY7VMvNGLTWdPd7nO2L0OXfK2hWoUyCNLyL4/83sgAeWplx8o5wxca7mp+i4=

install:
  - sudo apt-get install libportaudio-dev

script:
  - cargo build
  - cargo test
  - cargo doc

after_script:
  - cd target && curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
