language: rust

notifications:
  email:
    on_success: never
    on_failure: always

env:
  global:
  - secure: MXAUD2r9MRPY1KRySfmZ6gJ4gKcht6B/oE9+qtapXLeSOdNrHccPeWyCC4iNTeQ/tO2rWShvPfNbUpj+xECcC/tpGtQ6Sok3Vu2Xm3guCGhFAttsgg7UC2527R+KtIGe//ybBLxboVopR3LZ6Z706/C0RffEGkFY38MnqvL3To0=

sudo: false

addons:
  apt:
    packages:
    - portaudio19-dev

script:
- cargo build
- cargo test
- cargo doc --no-deps
- rustdoc --test README.md -L target/debug -L target/debug/deps

after_success:
- ".travis/publish_doc.sh"
