[package]
name = "portaudio-rs"
version = "0.3.2"
authors = ["mvdnes <git@mathijs.vd-nes.nl>"]
description = "PortAudio bindings for Rust"
license = "MIT"

[lib]
name = "portaudio_rs"

[dependencies]
bitflags = "1"
libc = "0.2"
portaudio-sys = { path = "portaudio-sys", version = "0.1" }
