[package]

name = "portaudio"
version = "0.0.1"
authors = ["mvdnes <git@mathijs.vd-nes.nl>"]

[dependencies.portaudio-sys]
path = "portaudio-sys"

[dependencies]
bitflags = "*"

[[bin]]
name = "test"
test = false
doc = false

[[bin]]
name = "demo"
test = false
doc = false
